### ISSUE TITLE
Dockerfile tests fail

### ISSUE THREAD

**Issue by oliverklee** [evilmartians/ruby-on-whales#10]
https://github.com/evilmartians/ruby-on-whales/runs/5643222494?check_suite_focus=true

```
 DockerfileTest
  test_default_dockerfile                                         FAIL (6.57s)
        Expected "ARG RUBY_VERSION\nARG DISTRO_NAME=bullseye\n\nFROM ruby:$RUBY_VERSION-slim-$DISTRO_NAME\n\nARG DISTRO_NAME\n\n# Common dependencies\nRUN apt-get update -qq \\\n  && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \\\n    build-essential \\\n    gnupg2 \\\n    curl \\\n    less \\\n    git \\\n  && apt-get clean \\\n  && rm -rf /var/cache/apt/archives/* \\\n  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \\\n  && truncate -s 0 /var/log/*log\n\n# Application dependencies\n# We use an external Aptfile for this, stay tuned\nCOPY Aptfile /tmp/Aptfile\nRUN apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get -yq dist-upgrade && \\\n  DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends \\\n    $(grep -Ev '^\\s*#' /tmp/Aptfile | xargs) \\\n    && apt-get clean \\\n    && rm -rf /var/cache/apt/archives/* \\\n    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \\\n    && truncate -s 0 /var/log/*log\n\n# Configure bundler\nENV LANG=C.UTF-8 \\\n  BUNDLE_JOBS=4 \\\n  BUNDLE_RETRY=3\n\n# Store Bundler settings in the project's root\nENV BUNDLE_APP_CONFIG=.bundle\n\n# Uncomment this line if you want to run binstubs without prefixing with `bin/` or `bundle exec`\n# ENV PATH /app/bin:$PATH\n\n# Upgrade RubyGems and install the latest Bundler version\nRUN gem update --system && \\\n    gem install bundler\n\n# Create a directory for the app code\nRUN mkdir -p /app\nWORKDIR /app\n\n# Document that we're going to expose port 3000\nEXPOSE 3000\n# Use Bash as the default command\nCMD [\"/usr/bin/bash\"]\n" to include "RUN curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add".
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:79:in `assert_file_contains'
        test/generator/dockerfile_test.rb:17:in `test_default_dockerfile'
```

**Comment by oliverklee** [comment]
Fixed by #5. Closing.
