### ISSUE TITLE
Test failures on CI in NodeTest

### ISSUE THREAD

**Issue by oliverklee** [evilmartians/ruby-on-whales#12]
https://github.com/evilmartians/ruby-on-whales/pull/11/checks

```
NodeTest
  test_default_node_versions                                      FAIL (1.26s)
        Expected to print line: Which Node version do you want to install? (Press ENTER to use 16, type 'n/no' to skip installing Node). Got: <ER to use 16, type 'n/no' to skip installing Node) 
        <o install? (Press ENTER to install the latest one) 
        NODE_VERSION=16
        YARN_VERSION=latest
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:71:in `assert_line_printed'
        test/generator/node_test.rb:16:in `block in test_default_node_versions'
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:61:in `block (2 levels) in run_generator'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/open3.rb:227:in `popen_run'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:54:in `block in run_generator'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler.rb:399:in `block in with_unbundled_env'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler.rb:698:in `with_env'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler.rb:399:in `with_unbundled_env'
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:51:in `run_generator'
        test/generator/node_test.rb:14:in `test_default_node_versions'

  test_custom_node_versions                                       FAIL (1.24s)
        Expected to print line: Which Node version do you want to install? (Press ENTER to use 16, type 'n/no' to skip installing Node). Got: <ER to use 16, type 'n/no' to skip installing Node) 14
        <o install? (Press ENTER to install the latest one) 1.13.0
        NODE_VERSION=14
        YARN_VERSION=1.13.0
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:71:in `assert_line_printed'
        test/generator/node_test.rb:41:in `block in test_custom_node_versions'
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:61:in `block (2 levels) in run_generator'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/open3.rb:227:in `popen_run'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/3.0.0/open3.rb:209:in `popen2e'
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:54:in `block in run_generator'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler.rb:399:in `block in with_unbundled_env'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler.rb:698:in `with_env'
        /opt/hostedtoolcache/Ruby/3.0.3/x64/lib/ruby/gems/3.0.0/gems/bundler-2.3.9/lib/bundler.rb:399:in `with_unbundled_env'
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:51:in `run_generator'
        test/generator/node_test.rb:39:in `test_custom_node_versions'

  test_skip_node                                                  FAIL (1.25s)
        Expected to print line: Which Node version do you want to install? (Press ENTER to use 16, type 'n/no' to skip installing Node). Got: <ER to use 16, type 'n/no' to skip installing Node) n
        NODE_VERSION=nope
        YARN_VERSION=
        /home/runner/work/ruby-on-whales/ruby-on-whales/test/test_helper.rb:71:in `assert_line_printed'

```

**Comment by palkan** [comment]
See https://github.com/evilmartians/ruby-on-whales/issues/14#issuecomment-1080584681
